/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_aion_avm_loader_Loader */

#ifndef _Included_org_aion_avm_loader_Loader
#define _Included_org_aion_avm_loader_Loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    createAccount
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_createAccount
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    hasAccountState
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_aion_avm_loader_Loader_hasAccountState
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    putCode
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_putCode
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    getCode
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_getCode
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    putStorage
 * Signature: (J[B[B[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_putStorage
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    getStorage
 * Signature: (J[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_getStorage
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    deleteAccount
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_deleteAccount
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    getBalance
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_getBalance
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    increaseBalance
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_increaseBalance
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    decreaseBalance
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_decreaseBalance
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    getNonce
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_org_aion_avm_loader_Loader_getNonce
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    incrementNonce
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_incrementNonce
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    getTransformedCode
 * Signature: (J[BB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_getTransformedCode
  (JNIEnv *, jclass, jlong, jbyteArray, jbyte);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    setTransformedCode
 * Signature: (J[B[BB)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_setTransformedCode
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jbyte);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    getObjectGraph
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_getObjectGraph
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    setObjectGraph
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_setObjectGraph
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    touchAccount
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_touchAccount
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    addLog
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_addLog
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    sendSignal
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_sendSignal
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    contract_address
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_contract_1address
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    getBlockHashByNumber
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_getBlockHashByNumber
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    sha256
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_sha256
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    blake2b
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_blake2b
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    keccak256
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_avm_loader_Loader_keccak256
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    edverify
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_aion_avm_loader_Loader_edverify
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_aion_avm_loader_Loader
 * Method:    removeStorage
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_org_aion_avm_loader_Loader_removeStorage
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
