[package]
description = "Recursive-length prefix encoding, decoding, and compression"
repository = "https://github.com/paritytech/parity"
license = "MIT/Apache-2.0"
name = "rlp"
version = "0.2.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
elastic-array = "0.9"
aion-types = { path = "../../util/aion-types"}
ethbloom = { path = "../../util/ethbloom"}
rustc-hex = "1.0"
byteorder = "1.0"

[features]
benches = []
