[package]
name = "equihash"
version = "0.1.0"
edition = "2018"

[dependencies]
blake2b = { path = "../blake2b" }
acore-bytes = { path = "../bytes" }
log = "0.3"

[dev-dependencies]
rustc-hex = "2.0.1"