[package]
name = "blake2b"
version = "0.1.0"
authors = ["Michael Gehring <mg@ebfe.org>"]
edition = "2018"

[dependencies]
aion-types = { path = "../../util/aion-types"}

[dev-dependencies]
tiny-keccak = "1.0"