[package]
name = "keychain-bin"
version = "0.1.0"
authors = ["Aion Foundation <admin@aion.network>"]
edition = "2018"

[dependencies]
docopt = "0.8"
num_cpus = "1.6"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
parking_lot = "0.5"
keychain = { path = "../" }
dir = { path = '../../../util/dir' }
panic_hook = { path = "../../../util/panic_hook" }

[[bin]]
name = "keychain"
path = "src/main.rs"
doc = false
