[package]
name = "rlp_compress"
version = "0.1.0"
authors = ["Aion Foundation <admin@aion.network>"]
edition = "2018"

[dependencies]
rlp = { path = "../rlp" }
elastic-array = "0.9"
lazy_static = "1.0"
